modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL=""
displayURL=""
license="All Rights Reserved"

[[mods]]
modId="capable"
version="${file.jarVersion}"
displayName="Capable"
description='''A mod to add a little bit of everything'''
itemIcon=""
configBackground=""

[[dependencies.capable]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="BOTH"

[[dependencies.capable]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.capable]]
modId="geckolib3"
mandatory=true
versionRange="[3.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.capable]]
modId="projecte"
mandatory=false
versionRange="[PE1.0,]"
ordering="AFTER"
side="BOTH"

[[dependencies.capable]]
modId="jeresources"
mandatory=false
versionRange="[0.12,]"
ordering="AFTER"
side="BOTH"
